[package]
name = "client"
version = "0.1.0"
authors = ["S.J.R. van Schaik", "Andrew Wheeler <genusistimelord@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
resolver = "2"

[dependencies]
bytemuck = { version = "1.14.0", features = ["derive"] }
mint = "0.5.9"
thiserror = "1.0.56"
winit = { version = "0.29.10", features = ["serde", "rwh_05"] }
image = "0.24.7"
tokio = { version = "1.32.0", features = ["full"] }
guillotiere = "0.6.2"
log = { version = "0.4.20", default-features = false }
backtrace = "0.3.69"
futures = "0.3.28"
chrono = { version = "0.4.30", disable-defaults = true, features = ["clock", "serde", "std"] }
ubits = "0.3.1"
hecs = {version="0.10.4", features = ["column-serialize", "row-serialize", "macros"] }
glam = { version = "0.24.1", features = ["bytemuck", "mint"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.82"
indexmap = "2.1.0"
slab = "0.4.9"
arboard = "3.3.1"
mio = { version = "0.8.10", features = ["os-poll", "net"] }
bytey = {version = "0.3.0", git = "https://github.com/Stefanowhb/bytey.git"}
pki-types = { package = "rustls-pki-types", version = "1", features = ["std"] }
rcgen = { version = "0.12", features = ["pem", "ring"], default-features = false }
rustls = { version = "0.22.2", features = ["logging"]}
toml = "0.8.10"
rustls-pemfile = "2"
webpki-roots = "0.26"
webpki = "0.22.4"
serde_repr = "0.1.18"
phf = { version = "0.11.2", features = ["macros"] }
regex = "1.10.3"
derivative = "2.2.0"

[dependencies.camera]
git = "https://github.com/AscendingCreations/AscendingLibraries"
#path = "../AscendingLibraries/camera"
#rev = "f2324c1"
package = "ascending_camera"
version = "0.1.0"

[dependencies.input]
git = "https://github.com/AscendingCreations/AscendingLibraries"
#path = "../AscendingLibraries/input"
#rev = "f2324c1"
package = "ascending_input"
version = "0.1.0"

[dependencies.graphics]
git = "https://github.com/AscendingCreations/AscendingLibraries"
#path = "../AscendingLibraries/graphics"
#rev = "f2324c1"
package = "ascending_graphics"
version = "0.1.0"