[package]
name = "client"
version = "0.1.0"
authors = ["S.J.R. van Schaik", "Andrew Wheeler <genusistimelord@outlook.com"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
thiserror = "1.0.56"
winit = { version = "0.29.15", features = ["serde", "rwh_05"] }
image = "0.24.7"
tokio = { version = "1.37.0", features = ["full"] }
log = { version = "0.4.21", default-features = false }
backtrace = "0.3.71"
chrono = { version = "0.4.30", disable-defaults = true, features = [
    "clock",
    "serde",
    "std",
] }
hecs = { version = "0.10.4", features = [
    "column-serialize",
    "row-serialize",
    "macros",
] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
indexmap = "2.2.6"
rodio = "0.17.3"
slab = "0.4.9"
arboard = "3.3.1"
mio = { version = "0.8.11", features = ["os-poll", "net"] }
bytey = { version = "0.3.0", git = "https://github.com/Stefanowhb/bytey.git" }
mmap_bytey = "0.2.0"
pki-types = { package = "rustls-pki-types", version = "1", features = ["std"] }
rcgen = { version = "0.12", features = [
    "pem",
    "ring",
], default-features = false }
rustls = { version = "0.23.4", default-features = false, features = [
    "logging",
    "ring",
    "std",
    "tls12",
] }
toml = "0.8.10"
rustls-pemfile = "2"
webpki-roots = "0.26"
webpki = "0.22.4"
regex = "1.10.3"
educe = { version = "0.5.11", default-features = false, features = [
    "Debug",
    "PartialEq",
    "Default",
] }
rand = "0.8.5"
bit_op = "0.1.1"
slotmap = "1.0.7"
lru = "0.12.3"
speedy = "=0.8.7"

[dependencies.camera]
package = "ascending_camera"
git = "https://github.com/AscendingCreations/AscendingLibraries"
#path = "../AscendingLibraries/camera"
version = "0.1.1"

[dependencies.input]
package = "ascending_input"
git = "https://github.com/AscendingCreations/AscendingLibraries"
#path = "../AscendingLibraries/input"
version = "0.2.1"

[dependencies.graphics]
package = "ascending_graphics"
git = "https://github.com/AscendingCreations/AscendingLibraries"
#path = "../AscendingLibraries/graphics"
version = "0.6.0"

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
strip = "none"
lto = false
incremental = true
panic = 'unwind'
codegen-units = 256
rpath = false

[profile.release]
opt-level = 3
debug = false
strip = "none"
debug-assertions = false
overflow-checks = true
lto = true
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.dev.package."*"]
opt-level = 2
