username = "test@test.com2"
password = "test"
save_password = true
bgm_volume = 70
sfx_volume = 70
reconnect_code = "hbrfVesNMcBpi28ZYgAZEthhr7MO5rkB"
level_filter = "Info"
enable_backtrace = false
graphic_backend = "OpenGL|DX12|Vulkan|Metal"
show_fps = true
power_settings = "HighPower"
present_mode = "AutoVsync"
gpu_instance = "None"
