bgm_volume = 0
enable_backtrace = false
gpu_instance = "None"
graphic_backend = "OpenGL|DX12|Vulkan|Metal"
level_filter = "Info"
password = ""
power_settings = "HighPower"
present_mode = "AutoVsync"
reconnect_code = "MrnZGKhBijbW8bNrt0sorxR7yWc2sNAP"
save_password = true
sfx_volume = 0
show_average_ping = true
show_fps = true
show_frame_loop = true
show_ping = true
username = ""
