username = "sherwin@test.com"
password = "test"
save_password = true
bgm_volume = 0
sfx_volume = 70
reconnect_code = "5BVSjEoniX30lMjKUw1MTlAaI5T8Ck1v"
level_filter = "Info"
enable_backtrace = false
graphic_backend = "OpenGL|DX12|Vulkan|Metal"
show_fps = false
show_ping = false
power_settings = "HighPower"
present_mode = "AutoVsync"
gpu_instance = "None"
