username = "sherwin@test.com"
password = "test"
save_password = true
bgm_volume = 7
sfx_volume = 7
reconnect_code = "0swpx4BA4YPE0jK51bDwdv8DCCHfzI15"
level_filter = "Info"
enable_backtrace = false
graphic_backend = "OpenGL|DX12|Vulkan|Metal"
show_fps = true
power_settings = "HighPower"
present_mode = "AutoVsync"
gpu_instance = "None"
