username = "sherwin@test.com"
password = "test"
save_password = true
bgm_volume = 0
sfx_volume = 0
reconnect_code = "DcyTaTa3f9JgWwUda4mRshuzF6F42Mrw"
level_filter = "Info"
enable_backtrace = false
graphic_backend = "OpenGL|DX12|Vulkan|Metal"
show_fps = true
power_settings = "HighPower"
present_mode = "AutoVsync"
gpu_instance = "None"
