username = "test3@email.com"
password = "test"
save_password = true
bgm_volume = 0
sfx_volume = 0
reconnect_code = "cmjl61qda3y198cr3oh8pj0xYgQYD6qD"
level_filter = "Info"
enable_backtrace = false
graphic_backend = "OpenGL|DX12|Vulkan|Metal"
show_fps = true
show_ping = true
show_average_ping = true
show_frame_loop = true
power_settings = "HighPower"
present_mode = "AutoVsync"
gpu_instance = "None"
