username = "sherwin@test.com"
password = "test"
save_password = true
bgm_volume = 7
sfx_volume = 7
reconnect_code = "FbmE3jX7IfLQAw5weisyVs12JuYGXOVO"
level_filter = "Info"
enable_backtrace = false
graphic_backend = "OpenGL|DX12|Vulkan|Metal"
show_fps = false
show_ping = true
power_settings = "HighPower"
present_mode = "AutoVsync"
gpu_instance = "None"
