username = "sherwin@test.com"
password = "test"
save_password = true
<<<<<<< HEAD
bgm_volume = 1
sfx_volume = 7
reconnect_code = "iJShJE02o2NCgWPmq4dHvY9vSsV6Tami"
=======
bgm_volume = 0
sfx_volume = 70
reconnect_code = "ZlCFuZ4VIIszlW7G9HX8AqseHqdjfxfC"
>>>>>>> b7c167be664882a51e61f369e735547084a2c7dd
level_filter = "Info"
enable_backtrace = false
graphic_backend = "OpenGL|DX12|Vulkan|Metal"
show_fps = true
show_ping = true
power_settings = "HighPower"
present_mode = "AutoVsync"
gpu_instance = "None"
