listen = '0.0.0.0:7010'
certs = 'keys/client.cer'
server_key = 'keys/client.key'
client_key = 'keys/ca.pem'
maxconnections = 500
database = 'ascending'
host = '127.0.0.1'
port = 5432
username = 'test'
password = 'test'