username = "sherwin@test.com"
password = "test"
save_password = true
bgm_volume = 0
sfx_volume = 70
reconnect_code = "ZlCFuZ4VIIszlW7G9HX8AqseHqdjfxfC"
level_filter = "Info"
enable_backtrace = false
graphic_backend = "OpenGL|DX12|Vulkan|Metal"
show_fps = true
show_ping = true
power_settings = "HighPower"
present_mode = "AutoVsync"
gpu_instance = "None"
